apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nejz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nejz
    app.kubernetes.io/part-of: byoc-app-geit
  name: nejz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: nejz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: nejz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-afqs-tenant/byoc-app-geit/nejz@sha256:df3ba6d47d08c2c49e5d7ce57b238f1f55c18923d80f890385cdb5acf42cc995
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
